#!/usr/bin/env bash

set -e

# Make sure this script is run from the same directory
dir=`pwd`
if [ ! -e "${dir}/$(basename $0)"  ]; then
  echo "Script not called from within repository directory. Aborting."
  exit 2
fi

# Symlink helper function
symlink() {
  # If this isnt a symlink (and the file exists)
  if [ ! -L "$2" ] && [ -f "$2" ]; then
    # Backup the file
    mv "$2" "$2.backup" >/dev/null 2>&1
    echo -e "$2 --> $2.backup"

    # Now remove it, dirs too
    rm -rf "$2" >/dev/null 2>&1
  fi

  # If this isnt a symlink (and the file exists)
  if [ ! -L "$2" ] && [ -d "$2" ]; then
    # Backup the file
    mv "$2" "$2.backup" >/dev/null 2>&1
    echo -e "$2 --> $2.backup"

    # Now remove it, dirs too
    rm -rf "$2" >/dev/null 2>&1
  fi

  # If the target is already a symlink
  if [ -L "$2" ]; then
    rm "$2" >/dev/null 2>&1
  fi

  # Create symlink
  ln -s $1 $2
  echo -e "$1 --> $2"
}

# Removes broken symlinks
clean_symlinks() {
  find -L . -maxdepth 1 -type l -exec rm -- {} +
}

setup_prompt() {
  npm install --global pure-prompt
}

# Install vim and plugins
setup_vim() {
  symlink ${dir}/vimrc ${HOME}/.vimrc
  symlink ${dir}/vim ${HOME}/.vim
  vim +PlugInstall +qall +silent
}

setup_tmux() {
  rm -rf ~/.tmux/plugins
  mkdir -p ~/.tmux/plugins
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  symlink ${dir}/tmux/tmux.conf ${HOME}/.tmux.conf
  ~/.tmux/plugins/tpm/scripts/install_plugins.sh
}

setup_git() {
  symlink ${dir}/gitconfig ${HOME}/.gitconfig
  symlink ${dir}/gitignore_global ${HOME}/.gitignore_global
}

# Symlink bash dotfiles
setup_zsh() {
  symlink ${dir}/zshrc ${HOME}/.zshrc
  symlink ${dir}/zsh/agnoster-modified.zsh-theme ${HOME}/.oh-my-zsh/custom/themes/agnoster-modified.zsh-theme
}

clean_symlinks
setup_vim
setup_git
setup_zsh
setup_tmux
setup_prompt
