" Load bundles
execute pathogen#infect()

set number
let t_Co=256
let mapleader=" "
set term=screen-256color
filetype off
syntax on
set undolevels=1000

colorscheme monokai

" Seoul settings
" let g:seoul256_background=237
" colo seoul256-light
" colo seoul256

" enable auto-complete plugin
" settings kept in seperate file
let g:neocomplcache_enable_at_startup = 1
source ~/.wells_dotfiles/vim/neocomplete_settings.vim

" session handling functions
" vim will save your open tabs and re-open them on return
source ~/.wells_dotfiles/vim/session_handling.vim

" status bar
set laststatus=2
set statusline=%4*\ %<%F%*              " full path
set statusline +=%2*%m%*                " modified flag
set statusline +=%1*%=%5l%*             " current line
set statusline +=%2*/%L%*               " total lines
set statusline +=%1*%4v\ %*             " virtual column number

set cursorline
set nocursorcolumn

" cntrl-o and p switch window splits
nmap <silent> <C-o> :wincmd h<CR>
nmap <silent> <C-p> :wincmd l<CR>

" Syntastic
let g:syntastic_check_on_open=1

" Tmux mouse fix (for resizing vim panes within tmux)
set mouse+=a
if &term =~ '^screen'
    " tmux knows the extended mouse mode
    set ttymouse=xterm2
endif

" Code folding settings
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=10        "this is just what i use

" tagbar
nmap ,, :TlistToggle<CR>

" Tab settings
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set smartindent
filetype on
filetype plugin on
filetype indent on

" Search Options
set incsearch
set hlsearch
nnoremap <c-h> :set hlsearch!<Cr>
nnoremap # #N
set ignorecase
set smartcase
noremap % v%

" Smooth scroll
nnoremap <CR> :call smooth_scroll#down(25, 20, 2)<cr>
nnoremap <silent> <c-d> :call smooth_scroll#down(15, 20, 2)<cr>
nnoremap <silent> <c-u> :call smooth_scroll#up(15, 20, 2)<cr>

" Fuzzy search runtime path
set rtp+=~/.fzf

" fuzzy finder shortcut call
nnoremap <c-t> :call fzf#run({'sink':'tabe'}) <Cr>

" I prefer gr to go back a tab
nnoremap gr gT

" F2 and F3 for saving and loading sessions
map <F2> :mksession! ~/vim_session <cr> " Quick write session with F2
map <F3> :source ~/vim_session <cr>     " And load session with F3

" Easy motion settings
map <Leader> <Plug>(easymotion-prefix)

" Nerd Tree Settings
nnoremap \ :NERDTreeTabsToggle<Cr>
let g:NERDTreeWinSize = 45
let NERDTreeShowHidden=1

" get rid of that annoying netrwhist file stuff
let g:netrw_dirhistmax = 0

" tab labels
let g:taboo_modified_tab_flag="+"
let g:taboo_tab_format=' %N. %f %m '

" MRU options
let MRU_Window_Height = 40
nnoremap m :MRU<cr>

" status line
let g:airline_powerline_fonts = 1
let g:airline_theme='jellybeans'
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"

""" CUSTOM COLORS """
"""
hi Visual ctermfg=black ctermbg=yellow
hi MatchParen cterm=none ctermfg=white ctermbg=blue
hi Search ctermfg=black ctermbg=yellow
hi IncSearch ctermfg=black ctermbg=yellow
hi TabLineSel ctermfg=black ctermbg=blue
hi TabLine ctermfg=black ctermbg=white
hi StatusLine ctermbg=yellow
