#!/bin/bash

. "${HOME}/.dotfiles/bash/install"

# Autoload include directory
for includeFile in $(find "${HOME}/.dotfiles/bash/includes" -type f ! -iname *.swp)
do
  . "${includeFile}"
done

EDITOR=vim
TZ=America/New_York
LANG=en_US.UTF-8
HISTFILE="${HOME}/.history"
HISTSIZE=10000

# auto enable colors for commands like 'ls'
CLICOLOR=1

export EDITOR TZ LANG HISTFILE HISTSIZE CLICOLOR

# Used by bash, unused by mksh
if [ "${0##*/}" = "bash" ] || [ "${0}" = "-bash" ] ; then
  shopt -s expand_aliases
  shopt -s checkwinsize
  HISTFILESIZE=2000
  HISTCONTROL=ignoredups:ignorespace
  export HISTFILESIZE HISTCONTROL
fi

# rbenv
if type -p rbenv >/dev/null 2>&1 ; then
  eval "$(rbenv init -)"
fi

# liquid prompt
source ~/.dotfiles/bash/liquidprompt/liquidprompt

# Load a local profile
[ -r "${HOME}/.localprofile" ] && . "${HOME}/.localprofile"

# automatically start ssh-agent and load ssh keys
if [ -z "$SSH_AUTH_SOCK" ] ; then
  eval `ssh-agent -s`
  ssh-add
fi

export GREP_OPTIONS='--color=auto'

# Update path
export PATH=$HOME/bin:$PATH
export PATH=$HOME/usr/local/sbin:$PATH
export PATH=$HOME/.bpkg/bin:"$PATH"

# better man pages
export PAGER=most
